### ISSUE TITLE
About the phase 1a message?

### ISSUE THREAD

**Issue by vision9527** [ajdavis/python-paxos-jepsen#1]
https://github.com/ajdavis/python-paxos-jepsen/blob/3a4cfa7bb067c08fb559ad0d299b3986f05134cc/paxos/core.py#L160-L166

Hi, Should the phase 1a message be sent just once(when not confilct) within proposer in the multi-decree parliament? The phase 1a message always is sent in this code when proposer have recieved client's request.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/25179277/165577027-6ff02a8e-08eb-4526-a0b5-7ca3e94912c2.png">

**Comment by ajdavis** [comment]
I think that the Proposer in my code *does* send the Phase 1a message only once.

* Someone executes `python client.py config-file 1`, where `1` is the proposed value.
* The client sends the request to *one* of the three servers.
* One of the servers receives the request and executes `client_request()` in `server.py`
* The request is passed to `Agent.receive()`, which puts the request in a `Queue`
* `Proposer.main_loop` pops the request from the `Queue` and passes it to `Proposer._handle_client_request`
* `Proposer._handle_client_request` sends the Phase 1a message

Once the request is popped from the queue on one server, that request is never processed again. So I believe the Phase 1a message is only sent once per client request. Do you see something different? Feel free to reopen.
